base: !include base.yaml

batch_size: 1
lr: 0.00025

model: "GNOFNOGNOAhmed"
subsample_train: 1
subsample_eval: 1
weighted_kernel: False

run_name: "GNOFNOGNO-r035"
project_name: "ahmed-body"

# dataset
data_path: "ahmed-body-dataset"
data_module: "AhmedBodyDataModule"
sdf_spatial_resolution: [64, 64, 64]

n_train: 2
n_test: 2