base: !include base.yaml
run_name: "RegDGCNN"
project_name: "RegDGCNN"

# train setting
num_epochs: 400
batch_size: 4
eval_batch_size: 4
lr: 0.001
device: cuda:0
eval_interval: 50

# model setting
mode: "train"
model: "RegDGCNN"
# in_channels: 4
# out_channels: 3 # velociy x, velociy y, velociy z
# num_levels: 4
# hidden_channels: 64
# use_position_input: True

# dataset setting
data_module: "CdDataModule"
train_data_dir: "../../xsy_datasets/CIKM_dataset/AIstudio_CIKM_dataset/Training/Dataset_2/Feature_File/"
test_data_dir: "../../xsy_datasets/CIKM_dataset/AIstudio_CIKM_dataset/Test/Dataset_2/Feature_File/"
sdf_spatial_resolution: [64, 64, 64]
point_data_pos: "press on mesh points"

# eval setting
write_to_vtk: false
out_keys: ["Cd"]
track: "Dataset_2_Cd"

#model
exp_name: "CdPrediction_DrivAerNet_r2_100epochs_5k"
cuda: True
seed: 1
num_points: 5000
# lr: 0.001
# batch_size: 2
epochs: 1
dropout: 0.4
emb_dims: 512
k: 40
optimizer: "adam"
#'channels': [6, 64, 128, 256, 512, 1024],
#'linear_sizes': [128, 64, 32, 16],
output_channels: 1
# dataset_path: r"D:\xunleixiazai\code-datasets-lib_folder\DrivAerNet_dataset\DrivAerNet_STLs_Combined"  # Update this with your dataset path
# aero_coeff: r"D:\xunleixiazai\code-datasets-lib_folder\DrivAerNet_dataset\AeroCoefficients_DrivAerNet_FilteredCorrected.csv"
# subset_dir: r"D:\xunleixiazai\code-datasets-lib_folder\DrivAerNet_dataset\subset_dir"
